# netlify.toml

[build]
  command = "echo 'Netlify build complete'" # Commande simple si pas de compilation JS/CSS
  functions = "lambda"                     # Le répertoire où Netlify trouvera vos fonctions
  publish = "public"                       # Le répertoire qui contient vos fichiers statiques (CSS, etc.)

# 1. Redirige TOUS les quiz statiques (quizzhtml/...)
# Notez que cela n'est plus nécessaire si vous utilisez le middleware Express statique 
# DANS la fonction, mais c'est plus propre de séparer les fichiers statiques. 

# 2. Redirige la page racine vers la fonction
[[redirects]]
  from = "/"
  to = "/.netlify/functions/index" # Redirige la racine vers la fonction 'index' dans le dossier 'lambda'
  status = 200                     # Important : Réécrit l'URL (cache le .netlify/functions)